seed: 42

paths:
  artifacts: artifacts
  models: ${paths.artifacts}/models
  predictions: ${paths.artifacts}/predictions
  reports: ${paths.artifacts}/reports

train_window:
  mode: cumulative_by_week
  start_season: 2012
  end_season: 2025
  include_preseason: false

evaluation:
  metrics:
    - log_loss
    - brier
    - roc_auc
    - accuracy
  reliability_diagram:
    bins: 12
  rank_calibration:
    buckets: [0.55, 0.60, 0.65, 0.70, 0.75]

outputs:
  persist_week_models: true
  write_predictions_csv: true
  prediction_probability_column: p_home_win

runtime:
  max_workers: 2
  ci_fast_folds: 1
  ci_fast_samples_per_week: 100
